name: paas-demo
services:
  transcryptor1:
    image: ghcr.io/nolai/paas-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis1
    volumes:
      - ./authentik.pem:/resources/public.pem:ro
      - ./access_rules.yml:/resources/access_rules.yml:ro
      - ./server_config1.yml:/resources/server_config.yml:ro
      - ./paas-config.json:/resources/paas_config.json:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      PAAS_SYSTEM_ID: PaaS-demo-1
      REDIS_URL: redis://redis1:6379
      JWT_AUDIENCE: PxRBbH97GBZzIL2ydSyfbtx90rXiXBpdeQJ1lJ6c
  redis1:
    image: redis:alpine

  transcryptor2:
    image: ghcr.io/nolai/paas-server:latest
    ports:
      - "8081:8080"
    depends_on:
      - redis2
    volumes:
      - ./authentik.pem:/resources/public.pem:ro
      - ./access_rules.yml:/resources/access_rules.yml:ro
      - ./server_config2.yml:/resources/server_config.yml:ro
      - ./paas-config.json:/resources/paas_config.json:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      PAAS_SYSTEM_ID: PaaS-demo-2
      REDIS_URL: redis://redis2:6379
      JWT_AUDIENCE: PxRBbH97GBZzIL2ydSyfbtx90rXiXBpdeQJ1lJ6c
  redis2:
    image: redis:alpine

  transcryptor3:
    image: ghcr.io/nolai/paas-server:latest
    ports:
      - "8082:8080"
    depends_on:
      - redis3
    volumes:
      - ./authentik.pem:/resources/public.pem:ro
      - ./access_rules.yml:/resources/access_rules.yml:ro
      - ./server_config3.yml:/resources/server_config.yml:ro
      - ./paas-config.json:/resources/paas_config.json:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      PAAS_SYSTEM_ID: PaaS-demo-3
      REDIS_URL: redis://redis3:6379
      JWT_AUDIENCE: PxRBbH97GBZzIL2ydSyfbtx90rXiXBpdeQJ1lJ6c
  redis3:
    image: redis:alpine

